version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
      - mvn --settings settings.xml clean deploy -Diam-user-access-key-id=XXXX -Diam-user-secret-key=XXXX
  post_build:
    commands:
      - cp ./settings.xml /root/.m2/settings.xml -DIAM_USER_ACCESS_KEY_ID=$IAM_USER_ACCESS_KEY_ID -DIAM_USER_ACCESS_KEY_SECRET=$IAM_USER_ACCESS_KEY_SECRET
      - mvn clean deploy
artifacts:
  files:
    - target/myawscdplanet-0.0.1-SNAPSHOT.jar
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'